#!/bin/bash

LOG=~/worklog.txt


CURRENT_STATE=$(cat $LOG | tail -1 | cut -f1 -d' ' --complement)
if [ "$CURRENT_STATE" == "ATWORK" ]; then
    echo "Already at work."
    exit
fi

workingon "At work"
echo `date +%s` "ATWORK" >> $LOG

HOURS=$(cat $LOG | tail -2 | cut -f1 -d' ' | tr '\n' ' ' | awk '{ print ($2 - $1)/60/60 " hours" }')
echo "You were at home for: $HOURS"
